pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                bat 'cd Backend/PC4MT && dotnet build'
            }
        }
        stage('Test') {
            steps {
                bat 'dotnet test'
            }
        }
        stage('Publish') {
            steps {
                bat 'dotnet publish -c release'
            }
        }
    }
}
