pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                // build steps here
            }
        }
        stage('Test') {
            steps {
                bat 'mstest /testcontainer:D:\glossloader\WebAppFile\GlossLoaderWebApp\Gloss Loader\Backend\PC4MT\MSTest Test Project\bin\Debug\MSTest Test Project.dll'
            }
        }
        stage('Publish') {
            steps {
                // publish steps here
            }
        }
    }
}
